export const capturedImageData = [
  {
    id: 1,
    mainTitle: "Lorem Ipsum Dolor Amet Conseteur",
    topSubTitle: "LOREM, IPSUM, NONUMY",
    bottomSubTitle: "Stet Clita - AMOR",
    src: require("Assets/Images/captured_img_1.jpg").default,
    fallback: require("Assets/Images/captured_img_1.webp").default,
    alt: "Chan image",
    bkg: "#111112",
  },
  {
    id: 2,
    mainTitle: "Lorem Ipsum Dolor Amet Conseteur",
    topSubTitle: "LOREM, IPSUM, NONUMY",
    bottomSubTitle: "Stet Clita - AMOR",
    src: require("Assets/Images/captured_img_2.jpg").default,
    fallback: require("Assets/Images/captured_img_2.webp").default,
    alt: "Ariana image",
    bkg: "#272727",
  },
  {
    id: 3,
    mainTitle: "Lorem Ipsum Dolor Amet Conseteur",
    topSubTitle: "LOREM, IPSUM, NONUMY",
    bottomSubTitle: "Stet Clita - AMOR",
    src: require("Assets/Images/captured_img_3.jpg").default,
    fallback: require("Assets/Images/captured_img_3.webp").default,
    alt: "Liz image",
    bkg: "#D0D5D8",
    fontColor: "#111112",
  },
  {
    id: 4,
    mainTitle: "Lorem Ipsum Dolor Amet Conseteur",
    topSubTitle: "LOREM, IPSUM, NONUMY",
    bottomSubTitle: "Stet Clita - AMOR",
    src: require("Assets/Images/captured_img_4.jpg").default,
    fallback: require("Assets/Images/captured_img_4.webp").default,
    alt: "Bailey image",
    bkg: "#111112",
  },
];
